version: '3.9'

name: sab-cdn

services:
  server:
    build:
      context: .
      args:
        - PORT=8080
    pull_policy: build
    image: sab-cdn:latest
    container_name: sab-cdn
    init: true
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 9000:8080
